apiVersion: v1
kind: Pod
metadata:
  name: sftp
  labels:
    app.kubernetes.io/name: sftp
spec:
  containers:
  - name: sftp
    image: sftp:edge
    command:
      - sh
      - -c
    args:
      - addgroup sftponly;
        adduser -h /home/bob  -G sftponly -D -u 4096 -s /bin/sh bob;
        echo bob:password | chpasswd;
        mkdir -p /jail/bob/home/bob/dev;
        chmod 755 /jail;
        chown bob:sftponly /jail/bob/home/bob;
        mkdir -p /etc/ssh/authorized_keys;
        echo ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJcv4iIMYaVC2Vw7uIaDvDv38yO9LT6aIpJMY5Xje1zb louis@tower > /etc/ssh/authorized_keys/bob;
        ulimit -n 10000;
        /usr/sbin/sshd -D -e
    ports:
      - name: ssh
        containerPort: 22
        protocol: TCP
    securityContext:
      capabilities:
        add: ["SYS_ADMIN"]
